### PR TITLE
Card Selection module

### PR DESCRIPTION
**Pull request by Apollonaut13**
Allows users to choose which card they want to see.

Example: https://i.gyazo.com/69c5ca0e44a27f323ac48436351847cd.mp4

### CODE REVIEW

**Comment by danrs** [comment]
@FreakyDug can you re-run the tests on this? It looks like it failed with a config error so I think just hitting rerun should make the tests go. I don't seem to have permission to hit that button (feel free to grant me permission on CircleCI if you like)

**Comment by Apollonaut13** [comment]
> @FreakyDug can you re-run the tests on this? It looks like it failed with a config error so I think just hitting rerun should make the tests go. I don't seem to have permission to hit that button (feel free to grant me permission on CircleCI if you like)

I can't run the tests on my machine, it requires too many modules that I don't have installed on the venv. I must have installed about 6 of them before reaching one that pip couldn't find for me. I updated the test files that have xwing wiki links on them, so hopefully it works now?

**Comment by FreakyDug** [comment]
> 
> 
> @FreakyDug can you re-run the tests on this? It looks like it failed with a config error so I think just hitting rerun should make the tests go. I don't seem to have permission to hit that button (feel free to grant me permission on CircleCI if you like)

I think the problem is @Apollonaut13's fork doesn't have the circleCI config file. Merging from master on the main repo should fix that.

**Comment by FreakyDug** [comment]
> 
> 
> > @FreakyDug can you re-run the tests on this? It looks like it failed with a config error so I think just hitting rerun should make the tests go. I don't seem to have permission to hit that button (feel free to grant me permission on CircleCI if you like)
> 
> I can't run the tests on my machine, it requires too many modules that I don't have installed on the venv. I must have installed about 6 of them before reaching one that pip couldn't find for me. I updated the test files that have xwing wiki links on them, so hopefully it works now?

You should only need to install `pytest` in addition to what's in `requirements.txt` in order for the tests to run. What other modules is it looking for?

**Comment by danrs** [comment]
Also, you can log in to circleci with your git creds to see what goes wrong when you have pushed a build. Testing before pushing is ideal, but being able to see circle output is useful too

**Comment by Apollonaut13** [comment]
I have no clue why it's giving so many errors.

**Comment by Apollonaut13** [comment]
> > > @FreakyDug can you re-run the tests on this? It looks like it failed with a config error so I think just hitting rerun should make the tests go. I don't seem to have permission to hit that button (feel free to grant me permission on CircleCI if you like)
> > 
> > 
> > I can't run the tests on my machine, it requires too many modules that I don't have installed on the venv. I must have installed about 6 of them before reaching one that pip couldn't find for me. I updated the test files that have xwing wiki links on them, so hopefully it works now?
> 
> You should only need to install `pytest` in addition to what's in `requirements.txt` in order for the tests to run. What other modules is it looking for?

after installing slackclient, my PyCharm says there isn't a module called 'slackclient'

**Pull request closed without merging**
